steps:
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['clean','install','-DskipTests']
    id: test
#  - name: eclipse-temurin:17-jdk
#    entrypoint: mvn
#    args: [ 'package','-Dmaven.test.skip=true' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/assignment3-428215/k8srepository/container1:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/assignment3-428215/k8srepository/container1:${SHORT_SHA}']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./container1deployment/
#      - --filename=./service1.yml
#      - --filename=./persistantvolume.yml
#      - --filename=./persistantvolumeclaim.yml
      - --location=us-central1-c
      - --cluster=cluster-assignment-3
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "./container2deployment/"
      - --location=us-central1-c
      - --cluster=cluster-assignment-3
options:
  logging: CLOUD_LOGGING_ONLY

