steps:
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['clean','install','-DskipTests']
    id: test
#  - name: eclipse-temurin:17-jdk
#    entrypoint: mvn
#    args: [ 'package','-Dmaven.test.skip=true' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/assignment3-428215/k8srepository/container1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/assignment3-428215/k8srepository/container1']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./container1deployment/
#      - --filename=./service1.yml
#      - --filename=./persistantvolume.yml
#      - --filename=./persistantvolumeclaim.yml
      - --location=us-central1-c
      - --cluster=cluster-assignment-3
  - name: 'google/cloud-sdk:latest'
    entrypoint: 'sh'
    args:
      - -xe
      - -c
      - |
        gcloud deploy apply --file ./container1deployment/deployment1.yaml --region=us-central1-c
options:
  logging: CLOUD_LOGGING_ONLY

