apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: us-central1-docker.pkg.dev/assignment3-428215/k8srepository/container1:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 6000
        volumeMounts:
          - name: data-volume
            mountPath: /harshil_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: host-pvc


